---
- name: 部署nginx
  hosts: node1
  vars: 
    ansible_user: root
  become: yes

  tasks:
    - name: 安装nginx
      yum:
        name: nginx
        state: present

    - name: 启动nginx
      service:
        name: nginx
        state: started
        enabled: yes
