---
- name: 停止nginx   #停止nginx
  hosts: 
    - node1  #指定目标主机组node1
    - node2  #指定目标主机组node2
  vars: 
    ansible_user: root  #指定用于连接远程主机的用户名
    ansible_ssh_private_key_file: /root/.ssh/id_rsa  #指定用于连接远程主机的私钥文件
  #因为上面ansible_user已指定连接远程主机用root了，所以这里无需提权到root.此外下面三个变量在/etc/ansible/ansible.cfg中也都可以配置
  # become: yes    #使用sudo提权
  # become_method: sudo #指定提权方法为sudo
  # become_user: root  #指定提权后的用户名

  tasks:
    - name: 安装nginx
      yum:
        name: nginx  #指定要安装的软件包名称
        state: present  #指定软件包的状态，present表示安装，如果已经安装则不做任何操作
        update_cache: yes #更新系统的软件包缓存
        
      
    - name: 停止nginx
      service:
        name: nginx  #指定要停止的服务名称
        state: stopped  #指定服务的状态，stopped表示停止，如果已经停止则不做任何操作
        enabled: no  #指定服务是否开机自启  
      when: inventory_hostname == 'node1' #当目标主机数据node1主机组时
      
    - name: 停止nginx
      service: 
        name: nginx  #指定要停止的服务名称
        state: stopped  #指定服务的状态，stopped表示停止，如果已经停止则不做任何操作
        enabled: no  #指定服务是否开机自启  
      when: inventory_hostname == 'node2' and ansible_distribution == 'Rocky' #当目标主机数据node2主机组并且时rocky linux时